// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the ROS 2 module
  docs: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        'module-1/index',
        'module-1/chapter-1-ros2-basics',
        'module-1/chapter-2-rclpy-ai-agents',
        'module-1/chapter-3-urdf-modeling',
      ],
    },
  ],

  // Manual sidebar configuration for the Digital Twin course
  digitalTwinCourse: [
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin-course/index',
        'digital-twin-course/physics-simulation-gazebo',
        'digital-twin-course/environment-design',
        'digital-twin-course/sensor-simulation',
      ],
    },
  ],

  // Manual sidebar configuration for the AI-Robot Brain course
  aiRobotBrain: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'ai-robot-brain-isaac/index',
        'ai-robot-brain-isaac/isaac-sim-photorealistic',
        'ai-robot-brain-isaac/isaac-ros-perception',
        'ai-robot-brain-isaac/nav2-navigation',
      ],
    },
  ],

  // Manual sidebar configuration for the VLA Robotics course
  vlaRobotics: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'vla-robotics/index',
        'vla-robotics/voice-to-action-pipeline',
        'vla-robotics/llm-cognitive-planning',
        'vla-robotics/vla-loop-humanoid-systems',
        'vla-robotics/capstone-overview',
      ],
    },
  ],
};

export default sidebars;
